### ISSUE TITLE
locum help field

### ISSUE THREAD

**Issue by kostyakch** [locumru/locum#5]
locum help

.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': undefined method `this' for #<Gem::Specification:0x3ff364a0502c locum-0.1.6> (NoMethodError)
	from .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/specification.rb:1057:in `find_active_stub_by_path'
	from .rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
	from .rvm/gems/ruby-2.3.0/gems/locum-0.1.6/bin/locum:5:in `<top (required)>'
	from .rvm/gems/ruby-2.3.0/bin/locum:23:in `load'
	from .rvm/gems/ruby-2.3.0/bin/locum:23:in `<main>'
	from .rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from .rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by vs-adm** [comment]
What is your `rubygems` version? Try to upgrade it first.

**Comment by vs-adm** [comment]
Seems to be stalled. Closing
